### ISSUE TITLE
Is there a more portable way to generate uuids?

### ISSUE THREAD

**Issue by nodesocket** [nodesocket/jsonlite#2]
Is `uuidgen` portable across most distributions? Is there a better option?

See: https://github.com/nodesocket/jsonlite/blob/master/jsonlite.bash#L71

**Comment by kmcheung12** [comment]
since you already require python, what about `UUID=$(python  -c 'import uuid; print uuid.uuid4()')`

**Comment by ehamiter** [comment]
`python -c 'import uuid;print(uuid.uuid4())` would handle both Python 2.x and 3.x.

**Comment by nodesocket** [comment]
Adding the PR @cbgbt gave to force uppercase of UUID's fixes some of the differences between distros using `uuidgen`.

See 0.4.1. https://github.com/nodesocket/jsonlite/blob/master/CHANGELOG.md
