### ISSUE TITLE
Add references between objects

### ISSUE THREAD

**Issue by piranna** [nodesocket/jsonlite#6]
Instead of having nested objects inside each JSON file, have plain JSON objects inside each of them and reference to other files by their UUID. This would also allow to use hashes to identify each object and have automatic deduplication.

**Comment by nodesocket** [comment]
This would significantly increase the complexity of `get` and `delete`. Get would have to traverse an object finding all references and inject them before returning.

Literally right now, we just do: `cat "$JSONLITE_PATH/$document_id"`

**Comment by nodesocket** [comment]
Probably not going to happen, at least not in the near future. Closing this issue for now.
