### ISSUE TITLE
support for "another" languages?

### ISSUE THREAD

**Issue by wallacesilva** [nodesocket/jsonlite#8]
this project will be support to "another" languages like php, javascript(nodejs), python e similars?

i created a version using php. (https://github.com/wallacesilva/phpjsonlite)

i loved this project :heart:

**Comment by nodesocket** [comment]
@wallacesilva the php version looks nice. I like that you followed the standards set.

1.) Uppercase UUID's
2.) Calling `get` and `delete` on a valid UUID, but one that does not exists, does not error, simply returns.
